AUTHOR = 'Jerome Tufte'
AUTHOR_SAVE_AS = False
SITENAME = 'Jerome Tufte | Blog'
# SITEURL = 'http://blog.jerometufte.me'
TIMEZONE = 'Africa/Johannesburg'
DEFAULT_DATE_FORMAT = '%b %d, %Y'
ARTICLE_URL = '{slug}'
CATEGORY_URL = 'category/{slug}'
TAG_URL = 'tag/{slug}'
PAGE_URL = 'pages/{slug}'
REVERSE_ARCHIVE_ORDER = True
THEME = 'content/theme'
# TYPOGRIFY = True
DEFAULT_PAGINATION = 10
DISQUS_SITENAME = 'tshepanglogs'